# Lecture 4: User defined functions


# Today: 2/5

1. Creating user defined functions, single and multivariable
2. Libraries
3. Return multiple variables; unpacking.
4. Default arguments, lambdas, docstrings.
5. Parameter (variable) scope.
6. Evaluate a function over a domain via looping (iteration).

ˆSee Hill Sec. 2.7 (Functions), except 2.7.5 (recursion).

## Creating Functions

Functions represent pieces of code you want to use repeatedly.

* Declared by using `def`, and indented afterwards
* They take *arguments* inside parentheses
* Can *return* things to the user

In [1]:
def square(x):
    x_squared = x**2
    return x_squared

alpha = square(3)
print(alpha)

9


## Libraries

Python has lots of *external libraries*, that are full of functions (and other things), you can use.

In [3]:
import math

print(math.sqrt(4))
print(math.pi, math.e)

2.0
3.141592653589793 2.718281828459045


## More About functions

Functions can have an unlimited number of arguments, and return an unlimited number of values, including `None`.

Functions can even call other functions

In [22]:
def printers(x):
    print(x)

beta = printers("hello")
print(beta)

""" return the sqrt of a^2 + b^2 """
def pythagoras(a,b):
    c = math.sqrt(a**2 + b**2)
    c_squared = square(c)

    return c, c_squared

hypotenuse = pythagoras(3,4)
print(hypotenuse)

hypo, hypo_squ = pythagoras(12,5)
print(hypo,hypo_squ)

hello
None
(5.0, 25.0)
13.0 169.0


### Args and Kwargs


Can pass arguments *positionally* or by *keyword*. The latter are called "**kwargs**"

In [7]:
pythagoras(5,12) #positional arguments
pythagoras(b=12,a=5) #keyword arguments

(13.0, 169.0)

Functions can also have default arguments

In [10]:

help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



And you can pass in the arguments as lists

`*` is the "splat" operator. It tells python to *unpack* the list.

In [13]:
triangle_sides = [5,12]
print(*triangle_sides)
pythagoras(*triangle_sides)

5 12


(13.0, 169.0)

### Lambda Functions

A special kind of "*anonymous*" function in python.

Take the form:
```
lambda <arguments> : <expression>
```

In [17]:
myfunc = lambda a: a+10
print(myfunc(5))

summer = lambda a, b : a+b
summer(1,2)

15


3

Functions can return other functions! Including lambdas. This will be helpful later in the class.

In [16]:
def my_scaling(n):
    return lambda g: g*n
#written a function that returns a function
tripler = my_scaling(3)
quadrupler = my_scaling(4)
print(tripler)

print(tripler(4))
print(quadrupler(4))
#lambda function are anonymous and don't need their input specified

<function my_scaling.<locals>.<lambda> at 0x00000206A8CC0720>
12
16


### Documentation

Document your code using *docstrings*. They become a `__doc__` attribute of the function.

In [23]:
print(pythagoras.__doc__) #help
help(pythagoras)

None
Help on function pythagoras in module __main__:

pythagoras(a, b)



## Scope

"Scope" describes where variables are valid.

**Local Variables**: variables declared *inside* functions, and *only* accessible *inside* the function

**Global Variables**: variables declared *outside* functions, and accesible everywhere

In [26]:
global_var = 2

def local_func():
    local_var = 3.
    print(f"My global variable {global_var}")

local_func()
print(local_var)

My global variable 2


NameError: name 'local_var' is not defined

Python "resolves" the meaning of variables in four steps (LEGB):

1. Locally
2. Enclosing (for nested functions)
3. Globally
4. Built-in (e.g. python built-in keywords like `range`)

In [33]:
a = 4
print(f"At declaration a = {a}")

def override():
   # global a
    a = "banana"
    print(f"Inside function a = {a}") 

override()

print(f"After the override function a = {a}")

At declaration a = 4
Inside function a = banana
After the override function a = 4


As a general rule: **define variables as locally as possible** and **do not re-use** variable names.

We also **strongly discourage** trying to modify a parameter from within a function. Instead, **return** it.

In [31]:
carrots = 3

def double_it(input):
    return input*2

extra_carrots = double_it(carrots)
print(extra_carrots)

6


If you are **sure** you want access to a doubly-named global variable (this is a bad idea usually!!), then you can use the `global` argument.

## Iteration

Sometimes we want to evalute a function many times. Python contains many helper routines!

We can use `linspace` or `arange` to define the domain of a function.

* `linspace`: specify start, stop, and number of points
* `arange`: specify start, stop, and size of jump


`arange` is quite similar to list(range(...))

In [37]:
import numpy as np 

x_vals = np.linspace(10,100,10)
print(x_vals)
#print(type(x_vals[0])
#better control over the value of 'junk'
x_vals_arange = np.arange(10, 100, 5)
print(x_vals_arange)
#print(type(x_vals_arange[0])
x_vals_range = range(10)
print(list(x_vals_range))

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


And can use np.zeros() to create an empty array to store the results of a function evaluation.

In [40]:
y_vals = np.zeros(len(x_vals))
print(y_vals)
y_vals = np.zeros_like(x_vals)
print(y_vals)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Use a for loop to evaluate a function of a single variable over a domain.

In [41]:
for i in range(len(x_vals)):
    y_vals[i] = square(x_vals[i])

print(y_vals)

[  100.   400.   900.  1600.  2500.  3600.  4900.  6400.  8100. 10000.]


## Bonus: Numpy vectorization

As a general rule, *looping* in python is *extremely inefficient*

Libraries like numpy contain clever vectorizations, that allow you to perform actions on whole arrays at once.

In [42]:
y_vals = square(x_vals)
print(y_vals)

[  100.   400.   900.  1600.  2500.  3600.  4900.  6400.  8100. 10000.]


### Speed Comparison 

We can do a quick speed comparison.

In [45]:
%%timeit
for i in range(len(x_vals)):
    y_vals[i] = square(x_vals[i])

2.19 μs ± 320 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [46]:
%%timeit
y_vals = square(x_vals)

506 ns ± 38.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
